# Default configuration for antichess RL training

model:
  input_channels: 19
  residual_blocks: 12
  filters: 256
  policy_head_size: 4096
  value_head_size: 256
  dropout_rate: 0.1

training:
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  epochs_per_iteration: 10
  games_per_iteration: 1000
  evaluation_games: 100

mcts:
  simulations: 800
  c_puct: 1.0
  temperature: 1.0
  temperature_threshold: 10
  dirichlet_alpha: 0.3
  dirichlet_epsilon: 0.25

system:
  num_workers: 4
  redis_host: "localhost"
  redis_port: 6379
  mongodb_uri: "mongodb://localhost:27017/"
  wandb_project: "antichess-rl"
  checkpoint_interval: 100
